apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.portainer.kubernetes.application.stack: monkeyradio
    io.kompose.service: monkeyradio
  name: monkeyradio
  namespace: monkeyradio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monkeyradio
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: monkeyradio
    spec:
      containers:
        - name: web
          env:
            - name: VUE_APP_MONKEY_NOW_PLAYING
              value: https://mydomain.com/now-playing
            - name: VUE_APP_MONKEY_STREAM
              value: https://mydomain.com/stream.mp3
          image: my-registry/monkeyradioreborn-web:0.1.1
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
            name: http-port
          livenessProbe:
            httpGet:
              port: 80
            periodSeconds: 10
        - name: now-playing
          image: my-registry/monkeyradioreborn-now-playing:0.2.1
          resources:
            requests:
              memory: "30Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          env:
            - name: ROCKET_SECRET_KEY
              value: MY SECRET KEY
          ports:
            - containerPort: 8000
              name:  api-port
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              port: 8000
              path: /now-playing
            periodSeconds: 10
        - name: icecast
          env:
            - name: ICE_RADIO_ADMIN_PASSWORD
              value: MYPASSWORD
            - name: ICE_RADIO_LISTEN_PORT
              value: "8092"
            - name: ICE_RADIO_SOURCE_PASSWORD
              value: MYPASSWORD
          image: riftbit/icecast:1.3.0
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "500m"
          ports:
            - containerPort: 8092
              name: stream-port
          livenessProbe:
            tcpSocket:
              port: 8092
            periodSeconds: 10
        - name: mpd
          ports:
            - containerPort: 6600
              name: mpd-port
          env:
            - name: ICECAST_MOUNT
              value: /stream.mp3
            - name: ICECAST_NAME
              value: Monkey Radio (Reborn)
            - name: ICECAST_PASSWORD
              value: MY PASSWORD
            - name: ICECAST_PORT
              value: "8092"
            - name: ICECAST_SERVER
              value: localhost
          image: my-registry/monkeyradioreborn-mpd:0.0.1
          livenessProbe:
            tcpSocket:
              port: 6600
            periodSeconds: 10
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /music
              name: music
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: music
          persistentVolumeClaim:
            claimName: monkey-radio-pvc
status: {}
