[package]
name = "monkeyradioreborn-now-playing"
version = "0.2.1"
authors = ["Zach Peters <zpeters@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
